name: locusproc
channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
- asn1crypto=0.22.0=py36_0
- ca-certificates=2017.4.17=0
- certifi=2017.4.17=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.2=py36_1
- cryptography=1.9=py36_0
- idna=2.5=py36_0
- libffi=3.2.1=3
- marshmallow=2.13.5=py36_0
- ncurses=5.9=10
- openssl=1.0.2l=0
- pip=9.0.1=py36_0
- pyaml=16.12.2=py36_0
- pycparser=2.18=py36_0
- pyopenssl=16.2.0=py36_0
- pysocks=1.6.7=py36_0
- python=3.6.1=3
- pyyaml=3.12=py36_1
- readline=6.2=0
- requests=2.18.1=py36_0
- setuptools=33.1.1=py36_0
- six=1.10.0=py36_1
- sqlite=3.13.0=1
- tk=8.5.19=1
- urllib3=1.21.1=py36_1
- wheel=0.29.0=py36_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.11=0

